---
- name: Deploy DNS Server
  hosts: all
  become: true

  vars:
    direct_viewing_area: "test.local"   #Имя для зоны прямого просмотра
    reverse_viewing_area: "0.168.192.in-addr.arpa" #Имя для зоны обратного просмотра
    directory_for_the_direct_viewing_zone: /var/named/{{ direct_viewing_area }} #создание файла для зоны прямого просмотра
    directory_for_the_reverse_viewing_zone: /var/named/{{ reverse_viewing_area }} #создание файла для зоны оьратного просмотра
    dns1_test_local: "dns1.{{ direct_viewing_area }}." #основная запись
    root_test_local: "root.{{ direct_viewing_area }}." #основная запись
    dns1_name: "dns1" 
    dns1_ip_address: "192.168.0.105"
    dns2_name: "Debian"
    dns2_ip_address: "192.168.0.110"
    dns1_reverse_ip: "105"
    dns1_reverse_name: "{{ dns1_test_local }}"
    dns2_reverse_ip: "110"
    dns2_reverse_name: "{{ dns2_name }}.{{ direct_viewing_area }}."


  tasks: 
  - block: #=======Block for REDHAT=======
    - name: Install packege "bind" for CentOS
      yum:
        name: bind 
        state: latest
      notify:
        - Started and Enabled named service

    - name: Put SELinux in permissive mode, logging actions that would be blocked for CentOS
      ansible.posix.selinux:
        policy: targeted
        state: permissive

    - name: Permissions for Firewalld for CentOS
      firewalld:
        service: dns 
        permanent: yes
        state: enabled 
      notify:
        - Restart Firewalld

    - name: Deploy file "named.conf" for CentOS
      template:
        src: named.conf.j2
        dest: /etc/named.conf

    - name: Creating a Direct View Zone file for CentOS
      template:
        src: direct_viewing_area.j2
        dest: "{{ directory_for_the_direct_viewing_zone }}"

    - name: Creating a Direct Reverse Zone file for CentOS
      template:
        src: reverse_viewing_area.j2
        dest: "{{ directory_for_the_reverse_viewing_zone }}"
      notify:
        - Restart named service

    when: ansible_os_family == "RedHat"


  handlers:
    - name: Started and Enabled named service
      service:
        name: named
        enabled: true
        state: started

    - name: Restart Firewalld
      service:
        name: firewalld
        state: restarted

    - name: Restart named service
      service: 
        name: named
        state: restarted
