---
- name: Started and Enabled named service
  service:
    name: named
    enabled: true
    state: started

- name: Restart Firewalld
  service:
    name: firewalld
    state: restarted

- name: Restart named service
  service: 
    name: named
    state: restarted

- name: Restart Apparmor service
  service:
    name: apparmor 
    state: restarted

- name: Restart Bind9 service
  service:
    name: bind9
    state: restarted